### ISSUE TITLE
Link to Awesome-XJTLU

### ISSUE THREAD

**Issue by chongfengling** [Survive-XJTLU-CS/SurviveXJTLUManual#10]
Hi, 很高兴有学弟学妹做《生存手册》。 我在一年前有维护过类似的项目[awesome-XJTLU](https://github.com/awesome-xjtlu/wiki)，因为毕业找不到人接管维护，所以更新停滞。如有合作想法（整合内容，添加链接等）欢迎联系～

**Comment by GothAngelS1nner** [comment]
> 找不到人接管维护，所以更新停滞。如有合作想法（整合内容，添加链接等）欢迎联系～

可以添加链接也欢迎提pr

**Comment by Wen-xuan-Xu** [comment]
> Hi, 很高兴有学弟学妹做《生存手册》。 我在一年前有维护过类似的项目[awesome-XJTLU](https://github.com/awesome-xjtlu/wiki)，因为毕业找不到人接管维护，所以更新停滞。如有合作想法（整合内容，添加链接等）欢迎联系～

友链可以 内容整合也欢迎  欢迎pr
