### ISSUE TITLE
希望将这个项目加入“XJTUL工作空间”的网站当中

### ISSUE THREAD

**Issue by Andynorior** [Survive-XJTLU-CS/SurviveXJTLUManual#14]
本人是西浦22级建筑学学生，这是用Notion搭建的一个网站，旨在整合网络上的各种资源，希望可以将学姐/学长的这个项目加入到网站当中，希望能够得到许可，我会在网站中介绍这个项目的功能与原作者
https://xjtlu.notion.site/XJTLU-3bfdab68044a4170a7be39b9bb93f192

**Comment by yc8272** [comment]
Sure! Thank you!
